name: Create Submission Report Via GitHub Action

on:
    workflow_dispatch:
permissions:
  contents: write

jobs:

  report:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'
    - name: Install gcovr from pip
      run: pip install gcovr
    - uses: actions/checkout@v4
    - name: Build Project
      run: make all
    - name: Create Submission Report
      run: ./scripts/create-submission-report.sh -m
    - name: GitHub Repo Info
      run: |
        echo "---" >> submission-report.md
        echo "GitHub repo: ${{ github.repository }}" >> submission-report.md
        if [ "${{ github.event.repository.visibility }}" == "public" ]; then
          echo "The repository visibility is public." >> submission-report.md
        elif [ "${{ github.event.repository.visibility }}" == "private" ]; then
            echo "The repository visibility is private." >> submission-report.md
        elif [ "${{ github.event.repository.visibility }}" == "internal" ]; then
            echo "The repository visibility is internal." >> submission-report.md
        fi
    - uses: docker://pandoc/core:3.5
      with:
        args: -s -o submission-report.docx submission-report.md

    - uses: stefanzweifel/git-auto-commit-action@v6
      with:
        commit_message: "Submission report created via GitHub Action"
